# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "eks-terragrunt-terraform-state-o1169f0t"
    dynamodb_table = "eks-terragrunt-terraform-state-lock"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "us-east-1"
  }
}
